/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.28 from the
 * contents of WiPi.xs. Do not edit this file, edit WiPi.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "WiPi.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"

#include <wiringPi.h>
#include <softPwm.h>

#line 21 "WiPi.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
	    Perl_croak_nocontext("Usage: %s::%s(%s)", hvname, gvname, params);
        else
	    Perl_croak_nocontext("Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
	Perl_croak_nocontext("Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#define croak_xs_usage        S_croak_xs_usage

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#if PERL_VERSION_LE(5, 21, 5)
#  define newXS_deffile(a,b) Perl_newXS(aTHX_ a,b,file)
#else
#  define newXS_deffile(a,b) Perl_newXS_deffile(aTHX_ a,b)
#endif

#line 165 "WiPi.c"

XS_EUPXS(XS_WiPi_setup_wipi); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_setup_wipi)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
#line 18 "WiPi.xs"
        wiringPiSetup();
#line 176 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_create_pwm); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_create_pwm)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, val");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	val = (int)SvIV(ST(1))
;
#line 27 "WiPi.xs"
        softPwmCreate(pin, val, 100);
#line 195 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_pin_mode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_pin_mode)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, val");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	val = (int)SvIV(ST(1))
;
#line 36 "WiPi.xs"
        pinMode(pin, val); 
#line 214 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_pwm_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_pwm_write)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, val");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	val = (int)SvIV(ST(1))
;
#line 45 "WiPi.xs"
        softPwmWrite(pin, val); 
#line 233 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_digital_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_digital_write)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, val");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	val = (int)SvIV(ST(1))
;
#line 54 "WiPi.xs"
        digitalWrite(pin, val);
#line 252 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_digital_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_digital_read)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;
#line 63 "WiPi.xs"
        RETVAL = digitalRead(pin);
#line 271 "WiPi.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_WiPi_i2c_setup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_i2c_setup)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dev");
    {
	int	dev = (int)SvIV(ST(0))
;
#line 73 "WiPi.xs"
        wringPiI2CSetup(dev);
#line 289 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_i2c_read); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_i2c_read)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "dev");
    {
	int	dev = (int)SvIV(ST(0))
;
	int	RETVAL;
	dXSTARG;
#line 81 "WiPi.xs"
        RETVAL = wiringPiI2CRead(dev);
#line 308 "WiPi.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_WiPi_i2c_read_reg8); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_i2c_read_reg8)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dev, regi");
    {
	int	dev = (int)SvIV(ST(0))
;
	int	regi = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 92 "WiPi.xs"
        RETVAL = wiringPiI2CReadReg8(dev, regi);
#line 330 "WiPi.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_WiPi_i2c_read_reg16); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_i2c_read_reg16)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dev, regi");
    {
	int	dev = (int)SvIV(ST(0))
;
	int	regi = (int)SvIV(ST(1))
;
	int	RETVAL;
	dXSTARG;
#line 103 "WiPi.xs"
        RETVAL = wiringPiI2CReadReg16(dev, regi);
#line 352 "WiPi.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_WiPi_i2c_write); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_i2c_write)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "dev, dat");
    {
	int	dev = (int)SvIV(ST(0))
;
	int	dat = (int)SvIV(ST(1))
;
#line 114 "WiPi.xs"
        wiringPiI2CWrite(dev, dat);
#line 372 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_i2c_write_reg8); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_i2c_write_reg8)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "dev, regi, dat");
    {
	int	dev = (int)SvIV(ST(0))
;
	int	regi = (int)SvIV(ST(1))
;
	int	dat = (int)SvIV(ST(2))
;
#line 124 "WiPi.xs"
        wiringPiI2CWriteReg8(dev, regi, dat);
#line 393 "WiPi.c"
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_WiPi_i2c_write_reg16); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_WiPi_i2c_write_reg16)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "dev, regi, dat");
    {
	int	dev = (int)SvIV(ST(0))
;
	int	regi = (int)SvIV(ST(1))
;
	int	dat = (int)SvIV(ST(2))
;
#line 134 "WiPi.xs"
        wiringPiI2CWriteReg16(dev, regi, dat);
#line 414 "WiPi.c"
    }
    XSRETURN_EMPTY;
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_WiPi); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_WiPi)
{
#if PERL_VERSION_LE(5, 21, 5)
    dVAR; dXSARGS;
#else
    dVAR; dXSBOOTARGSXSAPIVERCHK;
#endif
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(file);

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#if PERL_VERSION_LE(5, 21, 5)
    XS_VERSION_BOOTCHECK;
#  ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#  endif
#endif

        newXS_deffile("WiPi::setup_wipi", XS_WiPi_setup_wipi);
        newXS_deffile("WiPi::create_pwm", XS_WiPi_create_pwm);
        newXS_deffile("WiPi::pin_mode", XS_WiPi_pin_mode);
        newXS_deffile("WiPi::pwm_write", XS_WiPi_pwm_write);
        newXS_deffile("WiPi::digital_write", XS_WiPi_digital_write);
        newXS_deffile("WiPi::digital_read", XS_WiPi_digital_read);
        newXS_deffile("WiPi::i2c_setup", XS_WiPi_i2c_setup);
        newXS_deffile("WiPi::i2c_read", XS_WiPi_i2c_read);
        newXS_deffile("WiPi::i2c_read_reg8", XS_WiPi_i2c_read_reg8);
        newXS_deffile("WiPi::i2c_read_reg16", XS_WiPi_i2c_read_reg16);
        newXS_deffile("WiPi::i2c_write", XS_WiPi_i2c_write);
        newXS_deffile("WiPi::i2c_write_reg8", XS_WiPi_i2c_write_reg8);
        newXS_deffile("WiPi::i2c_write_reg16", XS_WiPi_i2c_write_reg16);
#if PERL_VERSION_LE(5, 21, 5)
#  if PERL_VERSION_GE(5, 9, 0)
    if (PL_unitcheckav)
        call_list(PL_scopestack_ix, PL_unitcheckav);
#  endif
    XSRETURN_YES;
#else
    Perl_xs_boot_epilog(aTHX_ ax);
#endif
}

